// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: business_token.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusinessToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                   // 版本号
	SecretId uint32 `protobuf:"varint,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"` // 密钥id 根据secretid获取key做解密
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                          // 加密信息
	Ctime    int64  `protobuf:"varint,4,opt,name=ctime,proto3" json:"ctime,omitempty"`                       // 创建时间戳 单位:秒
	Expire   int64  `protobuf:"varint,5,opt,name=expire,proto3" json:"expire,omitempty"`                     // 过期时间戳 单位:秒
}

func (x *BusinessToken) Reset() {
	*x = BusinessToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_token_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessToken) ProtoMessage() {}

func (x *BusinessToken) ProtoReflect() protoreflect.Message {
	mi := &file_business_token_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessToken.ProtoReflect.Descriptor instead.
func (*BusinessToken) Descriptor() ([]byte, []int) {
	return file_business_token_proto_rawDescGZIP(), []int{0}
}

func (x *BusinessToken) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BusinessToken) GetSecretId() uint32 {
	if x != nil {
		return x.SecretId
	}
	return 0
}

func (x *BusinessToken) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BusinessToken) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *BusinessToken) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

var File_business_token_proto protoreflect.FileDescriptor

var file_business_token_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x88, 0x01, 0x0a, 0x0d, 0x42, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x42, 0x16, 0x5a, 0x14, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_business_token_proto_rawDescOnce sync.Once
	file_business_token_proto_rawDescData = file_business_token_proto_rawDesc
)

func file_business_token_proto_rawDescGZIP() []byte {
	file_business_token_proto_rawDescOnce.Do(func() {
		file_business_token_proto_rawDescData = protoimpl.X.CompressGZIP(file_business_token_proto_rawDescData)
	})
	return file_business_token_proto_rawDescData
}

var file_business_token_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_business_token_proto_goTypes = []interface{}{
	(*BusinessToken)(nil), // 0: business_token.BusinessToken
}
var file_business_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_business_token_proto_init() }
func file_business_token_proto_init() {
	if File_business_token_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_business_token_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusinessToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_business_token_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_business_token_proto_goTypes,
		DependencyIndexes: file_business_token_proto_depIdxs,
		MessageInfos:      file_business_token_proto_msgTypes,
	}.Build()
	File_business_token_proto = out.File
	file_business_token_proto_rawDesc = nil
	file_business_token_proto_goTypes = nil
	file_business_token_proto_depIdxs = nil
}
